### 투표 리스트 조회
GET http://localhost:3000/api/votelist

### 투표 리스트 조회 - 인기 순
GET http://localhost:3000/api/votelist?offset=1&limit=8&order=popular

### 투표 리스트 조회 - 진행 중인 순
GET http://localhost:3000/api/votelist?order=open

### 투표 리스트 조회 (offset, limit)
GET http://localhost:3000/api/votelist?offset=17&limit=8

### 투표 리스트 조회 (search)
GET http://localhost:3000/api/votelist?search=테스트

### 투표 조회
GET http://localhost:3000/api/votelist/1

### 투표 생성
POST http://localhost:3000/api/vote
Content-Type: application/json

{
  "title": "테스트 10",
  "contents": ["1", "2", "3", "4"],
	"periodStart": "2024-05-15T00:00:00.000Z",
	"periodEnd": "2024-06-25T22:30:59.000Z",
	"method": "one",
	"participantNameMethod": "private",
	"hostName": "난 개발자",
	"password": "123412"
}

### 투표 수정
PUT  http://localhost:3000/api/vote/1
Content-Type: application/json

{
	"periodEnd": "2024-05-15T23:00:59.000Z",
  "password": "1234"
}

### 투표하기
POST http://localhost:3000/api/vote/1/1
# Content-Type: application/json

# {
#   "participantName": "이정윤"
# }

### 투표 삭제
DELETE http://localhost:3000/api/vote/54
Content-Type: application/json

{
  "password": "1234"
}