name: dev branch auto ci process script

on:
  push:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-noble-24.04

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /Vote_BE
            git pull origin main
            pm2 kill
            npm i --force
            npm run build
            pm2 start dist/server.js
